import {
  removeMultipleSpaces,
  removeEmptyLines,
  trimLines,
  removeAccents,
  removeNumbers,
  removeSpecialChars,
  removeEmojis,
  toUpperCase,
  toLowerCase,
  toTitleCase,
  capitalizeSentences,
  toSlug,
  toSnakeCase,
  toCamelCase,
  toPascalCase,
  reverseText,
  reverseWords,
  toBase64,
  fromBase64,
  toMockingCase,
  formatJson,
  csvToTable,
  markdownToHtml,
  sortLinesAsc,
  sortLinesDesc,
  sortLinesRandom,
  removeDuplicateLines,
  urlEncode,
  urlDecode
} from '../lib/textUtils'

export const cleaners = [
  { id: 'remove-multi-spaces', label: 'Quitar espacios múltiples', fn: removeMultipleSpaces, icon: '␣' },
  { id: 'remove-empty-lines', label: 'Quitar líneas vacías', fn: removeEmptyLines, icon: '¶' },
  { id: 'trim-lines', label: 'Recortar espacios', fn: trimLines, icon: '≫' },
  { id: 'remove-accents', label: 'Quitar tildes', fn: removeAccents, icon: 'á' },
  { id: 'remove-numbers', label: 'Quitar números', fn: removeNumbers, icon: '#' },
  { id: 'remove-symbols', label: 'Quitar símbolos', fn: removeSpecialChars, icon: '@' },
  { id: 'remove-emojis', label: 'Quitar emojis', fn: removeEmojis, icon: '☺' },
  { id: 'sort-asc', label: 'Ordenar A-Z', fn: sortLinesAsc, icon: '↑' },
  { id: 'sort-desc', label: 'Ordenar Z-A', fn: sortLinesDesc, icon: '↓' },
  { id: 'sort-random', label: 'Orden aleatorio', fn: sortLinesRandom, icon: '⇅' },
  { id: 'remove-dupes', label: 'Quitar duplicados', fn: removeDuplicateLines, icon: '∪' },
]

export const converters = [
  { id: 'to-upper', label: 'MAYÚSCULAS', fn: toUpperCase, group: 'case' },
  { id: 'to-lower', label: 'minúsculas', fn: toLowerCase, group: 'case' },
  { id: 'title-case', label: 'Tipo Título', fn: toTitleCase, group: 'case' },
  { id: 'capitalize', label: 'Capitalizar', fn: capitalizeSentences, group: 'case' },
  { id: 'mocking-case', label: 'Mocking Case', fn: toMockingCase, group: 'case' },
  { id: 'to-slug', label: 'slug-case', fn: toSlug, group: 'code' },
  { id: 'to-snake', label: 'snake_case', fn: toSnakeCase, group: 'code' },
  { id: 'to-camel', label: 'camelCase', fn: toCamelCase, group: 'code' },
  { id: 'to-pascal', label: 'PascalCase', fn: toPascalCase, group: 'code' },
  { id: 'reverse-text', label: 'Invertir Texto', fn: reverseText, group: 'text' },
  { id: 'reverse-words', label: 'Invertir Palabras', fn: reverseWords, group: 'text' },
  { id: 'url-encode', label: 'URL Encode', fn: urlEncode, group: 'data' },
  { id: 'url-decode', label: 'URL Decode', fn: urlDecode, group: 'data' },
  { id: 'to-base64', label: 'A Base64', fn: toBase64, group: 'data' },
  { id: 'from-base64', label: 'De Base64', fn: fromBase64, group: 'data' },
  { id: 'format-json', label: 'JSON Formato', fn: formatJson, group: 'data' },
  { id: 'csv-table', label: 'CSV a Tabla', fn: csvToTable, group: 'data', isHtml: true },
  { id: 'markdown', label: 'Markdown HTML', fn: markdownToHtml, group: 'data', isHtml: true },
]

export const converterGroups = ['case', 'code', 'text', 'data']
